#!/usr/bin/env python3
"""Generate ``manifests/terminal_wrench.yaml`` from a fetched Terminal Wrench clone.

Reads ``index/tasks.json`` (331 unique task ids among the per-model rows) and
optional ``task.toml`` files under ``tasks/{task_id}/claude-opus-4.6/original_task``.
``task_source_datasets.json`` supplies source-benchmark labels when present.

    python scripts/gen_terminal_wrench.py --repo-root /path/to/terminal-wrench

Re-run this script after bumping the pinned commit. The output file header
records the pin and this script's path.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

import yaml

TW_URL = "https://github.com/few-sh/terminal-wrench"
TW_COMMIT = "d8a29613235a0ef56a8b70b3142626a533da28c2"
MODEL_DIR = "claude-opus-4.6"
ENV_REL = Path(MODEL_DIR) / "original_task"
DEFAULT_TIMEOUT = 180
# Core TerminalAdapter defaults (Terminal-Bench-era). Most Terminal Wrench
# tasks differ: WORKDIR is usually /app, the gold script is solve.sh, and
# grading is tests/test.sh mounted at /tests — not /workspace/solution.sh
# and /tests/run-tests.sh.
CORE_DEFAULT_SUBMISSION_PATH = "/workspace/solution.sh"
CORE_DEFAULT_TEST_COMMAND = "bash /tests/run-tests.sh"
DEFAULT_WORKDIR = "/app"
TEST_SCRIPT_NAMES = ("test.sh", "run-tests.sh", "run_tests.sh")
_WORKDIR_RE = re.compile(r"^WORKDIR\s+(\S+)", re.IGNORECASE)

HEADER = """\
# Generated by scripts/gen_terminal_wrench.py — do not edit by hand.
# Re-run: python scripts/gen_terminal_wrench.py --repo-root <fetched TW clone>
#
# Pin: {url} @ {commit}
# Layout: tasks/<task_id>/claude-opus-4.6/original_task
# Images: adapter_config.image is verity-tw:<task_id>; build with
#   python scripts/build_images.py --repo-root <fetched TW clone>
#   (bakes original_task/tests at /tests — TB mounts this at grade time)
# Per-task adapter_config.submission_path / test_command / apply_command
# are inferred from the Dockerfile WORKDIR and tests/ filenames.
# Catalog: index/tasks.json, task_source_datasets.json
#
# Eight of 331 tasks have no claude-opus-4.6 copy in the upstream repo;
# their path still follows the pattern above. difficulty/category come from
# task.toml when that file is present.
"""


def unique_task_rows(tasks_index: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Keep one representative row per task_id (prefer the opus model row)."""
    by_id: dict[str, dict[str, Any]] = {}
    for row in tasks_index:
        task_id = str(row["task_id"])
        current = by_id.get(task_id)
        if current is None or (
            row.get("model") == MODEL_DIR and current.get("model") != MODEL_DIR
        ):
            by_id[task_id] = row
    return by_id


def _read_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def find_original_task(repo_root: Path, task_id: str) -> Path | None:
    """Return the on-disk ``original_task/`` directory for ``task_id``, if present."""
    preferred = repo_root / "tasks" / task_id / ENV_REL
    if preferred.is_dir():
        return preferred
    task_dir = repo_root / "tasks" / task_id
    if not task_dir.is_dir():
        return None
    matches = sorted(task_dir.glob("*/original_task"))
    return matches[0] if matches else None


def find_task_toml(repo_root: Path, task_id: str) -> Path | None:
    task_root = find_original_task(repo_root, task_id)
    if task_root is None:
        return None
    candidate = task_root / "task.toml"
    return candidate if candidate.is_file() else None


def dockerfile_workdir(dockerfile: Path) -> str:
    """Return the last ``WORKDIR`` in ``dockerfile``, or ``/app``.

    ``/app`` is the Terminal-Bench base-image default and the majority
    convention in the already-built Terminal Wrench sample. Tasks that
    set ``WORKDIR /workspace`` (or anything else) are picked up here.
    """
    try:
        text = dockerfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return DEFAULT_WORKDIR
    last: str | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = _WORKDIR_RE.match(line)
        if match is None:
            continue
        token = match.group(1).strip().strip("\"'")
        if token.startswith("["):
            token = token.strip("[]").split(",")[0].strip().strip("\"'")
        if token:
            last = token
    return last or DEFAULT_WORKDIR


def infer_test_command(tests_dir: Path) -> str | None:
    """Return the grading command for files in ``original_task/tests``.

    Terminal-Bench bind-mounts that directory at ``/tests``. Image builds
    bake the same layout, so the command uses ``/tests/...`` paths.
    """
    if not tests_dir.is_dir():
        return None
    for name in TEST_SCRIPT_NAMES:
        if (tests_dir / name).is_file():
            return f"bash /tests/{name}"
    if (tests_dir / "test_outputs.py").is_file():
        return "python3 -m pytest /tests/test_outputs.py -rA"
    return None


def with_workdir(command: str, workdir: str) -> str:
    """Prefix ``command`` with ``cd <workdir>`` when Core would run it elsewhere.

    Core's ``SandboxRunner`` always starts with workdir ``/workspace``, which
    is wrong for tasks whose Dockerfile ``WORKDIR`` is ``/app``: gold scripts
    write relative paths, and some pytest files invoke helpers like
    ``python3 interp.py`` against the image workdir.
    """
    if workdir in {"", ".", "/workspace"}:
        return command
    return f"cd {workdir} && {command}"


def wrap_test_command(test_command: str, workdir: str) -> str:
    """Run the task's test script, then honor Terminal-Bench's reward file.

    Core's TerminalAdapter treats the test command's exit code as the verdict.
    SETA-style ``test.sh`` (task 5 and most of this sample) always exits 0
    after writing ``/logs/verifier/reward.txt``; TB's harness reads that file.
    Scripts that already ``exit`` pytest's status still write the same file, so
    checking it is correct for both conventions. If the file is missing, fall
    back to the script's exit code.
    """
    inner = with_workdir(test_command, workdir)
    return (
        f"{inner}; _verity_s=$?; "
        "if [ -f /logs/verifier/reward.txt ]; then "
        "grep -qx 1 /logs/verifier/reward.txt; "
        "else exit $_verity_s; fi"
    )


def grading_adapter_config(task_root: Path | None) -> dict[str, Any]:
    """Fields Core's TerminalAdapter needs when they differ from its defaults."""
    if task_root is None:
        return {}
    dockerfile = task_root / "environment" / "Dockerfile"
    workdir = dockerfile_workdir(dockerfile) if dockerfile.is_file() else DEFAULT_WORKDIR
    submission_path = f"{workdir.rstrip('/')}/solve.sh"
    test_command = infer_test_command(task_root / "tests")
    apply_command = with_workdir(f"bash {submission_path}", workdir)
    config: dict[str, Any] = {}
    if submission_path != CORE_DEFAULT_SUBMISSION_PATH:
        config["submission_path"] = submission_path
    derived_apply = f"bash {submission_path}"
    if apply_command != derived_apply:
        config["apply_command"] = apply_command
    if test_command is not None:
        resolved_test = wrap_test_command(test_command, workdir)
        if resolved_test != CORE_DEFAULT_TEST_COMMAND:
            config["test_command"] = resolved_test
        # Stock test.sh installs uv/pytest over the network. Core disables
        # networking by default, which would fail authentic grading.
        config["limits"] = {"network_disabled": False}
    return config


def source_benchmark_for(
    task_id: str,
    row: dict[str, Any],
    source_map: dict[str, Any],
) -> tuple[str | None, list[str]]:
    raw = source_map.get(task_id)
    if isinstance(raw, list) and raw:
        labels = [str(item) for item in raw]
        return labels[0], labels
    datasets = row.get("source_datasets") or []
    if datasets:
        labels = [str(item) for item in datasets]
        return labels[0], labels
    if row.get("source_dataset"):
        label = str(row["source_dataset"])
        return label, [label]
    return None, []


def build_entry(
    task_id: str,
    row: dict[str, Any],
    *,
    repo_root: Path,
    source_map: dict[str, Any],
) -> dict[str, Any]:
    toml_path = find_task_toml(repo_root, task_id)
    meta_toml: dict[str, Any] = {}
    timeout = DEFAULT_TIMEOUT
    if toml_path is not None:
        parsed = _read_toml(toml_path)
        meta_toml = dict(parsed.get("metadata") or {})
        verifier = parsed.get("verifier") or {}
        if verifier.get("timeout_sec") is not None:
            timeout = int(verifier["timeout_sec"])

    primary, all_sources = source_benchmark_for(task_id, row, source_map)
    metadata: dict[str, Any] = {"dockerfile": "environment/Dockerfile"}
    if primary:
        metadata["source_benchmark"] = primary
    if len(all_sources) > 1:
        metadata["source_datasets"] = all_sources
    if meta_toml.get("difficulty"):
        metadata["difficulty"] = str(meta_toml["difficulty"])
    if meta_toml.get("category"):
        metadata["category"] = str(meta_toml["category"])
    if task_id.isdigit():
        metadata["upstream_task_id"] = task_id

    adapter_config: dict[str, Any] = {
        "timeout": timeout,
        "image": f"verity-tw:{task_id}",
    }
    adapter_config.update(grading_adapter_config(find_original_task(repo_root, task_id)))

    return {
        "name": task_id,
        "path": f"tasks/{task_id}/{ENV_REL.as_posix()}",
        "domain": {"category": "terminal", "subcategory": "bash"},
        "adapter": "terminal",
        "adapter_config": adapter_config,
        "metadata": metadata,
    }


def collect_entries(repo_root: Path) -> list[dict[str, Any]]:
    index_path = repo_root / "index" / "tasks.json"
    if not index_path.is_file():
        raise SystemExit(f"missing {index_path}; fetch Terminal Wrench first")
    tasks_index = json.loads(index_path.read_text(encoding="utf-8"))
    if not isinstance(tasks_index, list):
        raise SystemExit(f"{index_path} is not a JSON list")

    source_map: dict[str, Any] = {}
    sources_path = repo_root / "task_source_datasets.json"
    if sources_path.is_file():
        loaded = json.loads(sources_path.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):
            source_map = loaded

    by_id = unique_task_rows(tasks_index)

    def _sort_key(task_id: str) -> tuple[int, int | str]:
        if task_id.isdigit():
            return (0, int(task_id))
        return (1, task_id)

    return [
        build_entry(task_id, by_id[task_id], repo_root=repo_root, source_map=source_map)
        for task_id in sorted(by_id, key=_sort_key)
    ]


def render_manifest(entries: list[dict[str, Any]], *, commit: str = TW_COMMIT) -> str:
    document = {
        "source_defaults": {
            "type": "git",
            "url": TW_URL,
            "commit": commit,
        },
        "entries": entries,
    }
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=200)
    return HEADER.format(url=TW_URL, commit=commit) + "\n" + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--repo-root",
        type=Path,
        required=True,
        help="Fetched Terminal Wrench checkout containing index/tasks.json.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output YAML path (default: manifests/terminal_wrench.yaml in this repo).",
    )
    args = parser.parse_args(argv)
    repo_root = args.repo_root.expanduser().resolve()
    output = args.output
    if output is None:
        output = Path(__file__).resolve().parent.parent / "manifests" / "terminal_wrench.yaml"
    entries = collect_entries(repo_root)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_manifest(entries), encoding="utf-8")
    print(f"wrote {len(entries)} entries to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
