#!/usr/bin/env python3
"""Generate ``manifests/terminal_wrench.yaml`` from a fetched Terminal Wrench clone.

Reads ``index/tasks.json`` (331 unique task ids among the per-model rows) and
optional ``task.toml`` files under ``tasks/{task_id}/claude-opus-4.6/original_task``.
``task_source_datasets.json`` supplies source-benchmark labels when present.

    python scripts/gen_terminal_wrench.py --repo-root /path/to/terminal-wrench

Re-run this script after bumping the pinned commit. The output file header
records the pin and this script's path.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path
from typing import Any

import yaml

TW_URL = "https://github.com/few-sh/terminal-wrench"
TW_COMMIT = "d8a29613235a0ef56a8b70b3142626a533da28c2"
MODEL_DIR = "claude-opus-4.6"
ENV_REL = Path(MODEL_DIR) / "original_task"
DEFAULT_TIMEOUT = 180

HEADER = """\
# Generated by scripts/gen_terminal_wrench.py — do not edit by hand.
# Re-run: python scripts/gen_terminal_wrench.py --repo-root <fetched TW clone>
#
# Pin: {url} @ {commit}
# Layout: tasks/<task_id>/claude-opus-4.6/original_task
# Images: adapter_config.image is verity-tw:<task_id>; build with
#   python scripts/build_images.py --repo-root <fetched TW clone>
# Catalog: index/tasks.json, task_source_datasets.json
#
# Eight of 331 tasks have no claude-opus-4.6 copy in the upstream repo;
# their path still follows the pattern above. difficulty/category come from
# task.toml when that file is present.
"""


def unique_task_rows(tasks_index: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Keep one representative row per task_id (prefer the opus model row)."""
    by_id: dict[str, dict[str, Any]] = {}
    for row in tasks_index:
        task_id = str(row["task_id"])
        current = by_id.get(task_id)
        if current is None or (
            row.get("model") == MODEL_DIR and current.get("model") != MODEL_DIR
        ):
            by_id[task_id] = row
    return by_id


def _read_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def find_task_toml(repo_root: Path, task_id: str) -> Path | None:
    preferred = repo_root / "tasks" / task_id / ENV_REL / "task.toml"
    if preferred.is_file():
        return preferred
    task_dir = repo_root / "tasks" / task_id
    if not task_dir.is_dir():
        return None
    matches = sorted(task_dir.glob("*/original_task/task.toml"))
    return matches[0] if matches else None


def source_benchmark_for(
    task_id: str,
    row: dict[str, Any],
    source_map: dict[str, Any],
) -> tuple[str | None, list[str]]:
    raw = source_map.get(task_id)
    if isinstance(raw, list) and raw:
        labels = [str(item) for item in raw]
        return labels[0], labels
    datasets = row.get("source_datasets") or []
    if datasets:
        labels = [str(item) for item in datasets]
        return labels[0], labels
    if row.get("source_dataset"):
        label = str(row["source_dataset"])
        return label, [label]
    return None, []


def build_entry(
    task_id: str,
    row: dict[str, Any],
    *,
    repo_root: Path,
    source_map: dict[str, Any],
) -> dict[str, Any]:
    toml_path = find_task_toml(repo_root, task_id)
    meta_toml: dict[str, Any] = {}
    timeout = DEFAULT_TIMEOUT
    if toml_path is not None:
        parsed = _read_toml(toml_path)
        meta_toml = dict(parsed.get("metadata") or {})
        verifier = parsed.get("verifier") or {}
        if verifier.get("timeout_sec") is not None:
            timeout = int(verifier["timeout_sec"])

    primary, all_sources = source_benchmark_for(task_id, row, source_map)
    metadata: dict[str, Any] = {"dockerfile": "environment/Dockerfile"}
    if primary:
        metadata["source_benchmark"] = primary
    if len(all_sources) > 1:
        metadata["source_datasets"] = all_sources
    if meta_toml.get("difficulty"):
        metadata["difficulty"] = str(meta_toml["difficulty"])
    if meta_toml.get("category"):
        metadata["category"] = str(meta_toml["category"])
    if task_id.isdigit():
        metadata["upstream_task_id"] = task_id

    return {
        "name": task_id,
        "path": f"tasks/{task_id}/{ENV_REL.as_posix()}",
        "domain": {"category": "terminal", "subcategory": "bash"},
        "adapter": "terminal",
        "adapter_config": {
            "timeout": timeout,
            "image": f"verity-tw:{task_id}",
        },
        "metadata": metadata,
    }


def collect_entries(repo_root: Path) -> list[dict[str, Any]]:
    index_path = repo_root / "index" / "tasks.json"
    if not index_path.is_file():
        raise SystemExit(f"missing {index_path}; fetch Terminal Wrench first")
    tasks_index = json.loads(index_path.read_text(encoding="utf-8"))
    if not isinstance(tasks_index, list):
        raise SystemExit(f"{index_path} is not a JSON list")

    source_map: dict[str, Any] = {}
    sources_path = repo_root / "task_source_datasets.json"
    if sources_path.is_file():
        loaded = json.loads(sources_path.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):
            source_map = loaded

    by_id = unique_task_rows(tasks_index)

    def _sort_key(task_id: str) -> tuple[int, int | str]:
        if task_id.isdigit():
            return (0, int(task_id))
        return (1, task_id)

    return [
        build_entry(task_id, by_id[task_id], repo_root=repo_root, source_map=source_map)
        for task_id in sorted(by_id, key=_sort_key)
    ]


def render_manifest(entries: list[dict[str, Any]], *, commit: str = TW_COMMIT) -> str:
    document = {
        "source_defaults": {
            "type": "git",
            "url": TW_URL,
            "commit": commit,
        },
        "entries": entries,
    }
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    return HEADER.format(url=TW_URL, commit=commit) + "\n" + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--repo-root",
        type=Path,
        required=True,
        help="Fetched Terminal Wrench checkout containing index/tasks.json.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output YAML path (default: manifests/terminal_wrench.yaml in this repo).",
    )
    args = parser.parse_args(argv)
    repo_root = args.repo_root.expanduser().resolve()
    output = args.output
    if output is None:
        output = Path(__file__).resolve().parent.parent / "manifests" / "terminal_wrench.yaml"
    entries = collect_entries(repo_root)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_manifest(entries), encoding="utf-8")
    print(f"wrote {len(entries)} entries to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
